// Package main implements the Pulumi resource provider for DataMammoth.
//
// This provider is bridged from the Terraform provider using pulumi-terraform-bridge.
// See https://github.com/datamammoth/terraform-provider-datamammoth for the upstream
// Terraform provider.
//
// To build the bridge, the following steps are required:
//   1. Ensure the Terraform provider is published and versioned
//   2. Run `pulumi-terraform-bridge` to generate the Pulumi schema
//   3. Build this binary as `pulumi-resource-datamammoth`
//
// For development, this file serves as a placeholder. The actual bridge code
// will be auto-generated by the pulumi-terraform-bridge toolchain.
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Fprintln(os.Stderr, "pulumi-resource-datamammoth: not yet built — see README.md")
	os.Exit(1)
}
